version: '3.8'

services:
    react:
        image: androman/front_repository
        restart: always
        ports:
            - "3000:3000"
        environment:
            REACT_APP_API_URL: http://localhost:5001/api/
            REACT_APP_SERVER_URL: http://localhost:5001/
            REACT_APP_USER_IMAGE: http://localhost:5001/user/
volumes:
    postgres_data:
